
import java.util.Random;
import javax.swing.ImageIcon;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author AlbaracinAce
 */
public class gacha extends javax.swing.JFrame {

    /**
     * Creates new form gacha
     */
    public gacha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        un1 = new javax.swing.JLabel();
        un2 = new javax.swing.JLabel();
        un3 = new javax.swing.JLabel();
        un4 = new javax.swing.JLabel();
        un5 = new javax.swing.JLabel();
        un6 = new javax.swing.JLabel();
        un7 = new javax.swing.JLabel();
        un8 = new javax.swing.JLabel();
        un9 = new javax.swing.JLabel();
        un0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        urp = new javax.swing.JLabel();
        srp = new javax.swing.JLabel();
        rp = new javax.swing.JLabel();
        np = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 204, 255));
        setForeground(new java.awt.Color(0, 255, 255));

        jButton1.setText("Summon");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        un1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un1.setIconTextGap(10);
        un1.setMaximumSize(new java.awt.Dimension(0, 0));
        un1.setMinimumSize(new java.awt.Dimension(0, 0));
        un1.setPreferredSize(new java.awt.Dimension(50, 50));

        un2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un2.setMaximumSize(new java.awt.Dimension(50, 50));
        un2.setMinimumSize(new java.awt.Dimension(50, 50));
        un2.setPreferredSize(new java.awt.Dimension(50, 50));

        un3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un3.setMaximumSize(new java.awt.Dimension(50, 50));
        un3.setMinimumSize(new java.awt.Dimension(50, 50));
        un3.setPreferredSize(new java.awt.Dimension(50, 50));

        un4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un4.setMaximumSize(new java.awt.Dimension(50, 50));
        un4.setMinimumSize(new java.awt.Dimension(50, 50));
        un4.setPreferredSize(new java.awt.Dimension(50, 50));

        un5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un5.setMaximumSize(new java.awt.Dimension(50, 50));
        un5.setMinimumSize(new java.awt.Dimension(50, 50));
        un5.setPreferredSize(new java.awt.Dimension(50, 50));

        un6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un6.setMaximumSize(new java.awt.Dimension(50, 50));
        un6.setMinimumSize(new java.awt.Dimension(50, 50));
        un6.setPreferredSize(new java.awt.Dimension(50, 50));

        un7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un7.setMaximumSize(new java.awt.Dimension(50, 50));
        un7.setMinimumSize(new java.awt.Dimension(50, 50));
        un7.setPreferredSize(new java.awt.Dimension(50, 50));

        un8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un8.setMaximumSize(new java.awt.Dimension(50, 50));
        un8.setMinimumSize(new java.awt.Dimension(50, 50));
        un8.setPreferredSize(new java.awt.Dimension(50, 50));

        un9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un9.setMaximumSize(new java.awt.Dimension(50, 50));
        un9.setMinimumSize(new java.awt.Dimension(50, 50));
        un9.setPreferredSize(new java.awt.Dimension(50, 50));

        un0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        un0.setMaximumSize(new java.awt.Dimension(50, 50));
        un0.setMinimumSize(new java.awt.Dimension(50, 50));
        un0.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setText("Probability");

        jLabel2.setText("UR:");
        jLabel2.setPreferredSize(new java.awt.Dimension(25, 20));

        jLabel3.setText("SR:");
        jLabel3.setPreferredSize(new java.awt.Dimension(25, 20));

        jLabel4.setText("R:");
        jLabel4.setPreferredSize(new java.awt.Dimension(25, 20));

        jLabel5.setText("N:");
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 20));

        urp.setText("0.5%");
        urp.setPreferredSize(new java.awt.Dimension(45, 20));

        srp.setText("1.5%");
        srp.setPreferredSize(new java.awt.Dimension(45, 20));

        rp.setText("3%");
        rp.setPreferredSize(new java.awt.Dimension(45, 20));

        np.setText("5%");
        np.setPreferredSize(new java.awt.Dimension(45, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(un6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(un2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(un3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(un4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(un5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(un7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(un8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(un9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(un0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(un1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(un6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(un0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Random pg = new Random();
        String unit[] = {"UR", "SR", "R", "N"};

        String x;

        double xx1 = 0;
        double xx2 = 0;
        double xx3 = 0;
        double xx4 = 0;

        int number = 0;
        for (int counter = 1; counter <= 10; counter++) {
  ImageIcon imageur = new ImageIcon("bg.png");
            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un1.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un1.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un1.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = +5;
                un1.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un2.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un2.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un2.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = +5;
                un2.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un3.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un3.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un3.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = +5;
                un3.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un4.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un4.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un4.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = +5;
                un4.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un5.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un5.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un5.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = +5;
                un5.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un6.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un6.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un6.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = 5;
                un6.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un7.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un7.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un7.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = 5;
                un7.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un8.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un8.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un8.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = 5;
                un8.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un9.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un9.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un9.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = 5;
                un9.setText("      " + x);

            }

            number = pg.nextInt(1000);

            if (number <= 49) {
                x = unit[0];
                xx1 = 0.5;
                un0.setText("      " + x);

            }

            if (number <= 201 && number > 49) {

                x = unit[1];
                xx2 = 1.5;
                un0.setText("      " + x);

            }

            if (number <= 501 && number > 201) {
                x = unit[2];
                xx3 = 3;
                un0.setText("      " + x);

            }

            if (number <= 1001 && number > 501) {
                x = unit[3];
                xx4 = 5;
                un0.setText("      " + x);

            }
            
            
        }
 

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gacha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gacha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel np;
    private javax.swing.JLabel rp;
    private javax.swing.JLabel srp;
    private javax.swing.JLabel un0;
    private javax.swing.JLabel un1;
    private javax.swing.JLabel un2;
    private javax.swing.JLabel un3;
    private javax.swing.JLabel un4;
    private javax.swing.JLabel un5;
    private javax.swing.JLabel un6;
    private javax.swing.JLabel un7;
    private javax.swing.JLabel un8;
    private javax.swing.JLabel un9;
    private javax.swing.JLabel urp;
    // End of variables declaration//GEN-END:variables
}
